services:
  yt-dlp-m4a:
    build: .
    container_name: yt-dlp-m4a-downloader
    volumes:
      - ./Downloads:/app/Downloads  # Mount downloads directory inside the container
    environment:
      - PYTHONUNBUFFERED=1  # Keep logs printed to the console